version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
    - 9000:9000
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: db
    ports:
      - 35432:5432
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: db
    ports:
    - 3306:3306
  mailhog:
    image: mailhog/mailhog
    ports:
    - 1025:1025
