name: docker latest
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Publish Balerter to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: balerter/balerter
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"
        dockerfile: ./contrib/balerter.Dockerfile

    - name: Publish BalerterTest to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: balerter/test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"
        dockerfile: ./contrib/test.Dockerfile
