name: docker release
on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Publish Balerter to Registry Release
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: balerter/balerter
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
        dockerfile: ./contrib/balerter.Dockerfile

    - name: Publish BalerterTest to Registry Release
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: balerter/test
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
        dockerfile: ./contrib/test.Dockerfile

    - name: Publish tgtool to Registry Release
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: balerter/tgtool
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
        dockerfile: ./contrib/tgtool.Dockerfile
