name: docker release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: docker login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push - balerter/balerter
        run: |
          docker build -t balerter/balerter:latest -t balerter/balerter:${{ env.RELEASE_VERSION }} -f contrib/balerter.Dockerfile .
          docker push balerter/balerter:latest
          docker push balerter/balerter:${{ env.RELEASE_VERSION }}

      - name: build and push - balerter/test
        run: |
          docker build -t balerter/test:latest -t balerter/test:${{ env.RELEASE_VERSION }} -f contrib/test.Dockerfile .
          docker push balerter/test:latest
          docker push balerter/test:${{ env.RELEASE_VERSION }}
